### ISSUE TITLE
TextRange::from_len argument order may be unclear

### ISSUE THREAD

**Issue by CAD97** [rust-analyzer/text-size#34]
Real code snippet from rowan (https://github.com/CAD97/rowan/pull/3)

```rust
        TextRange::from_len(self.offset, TextSize::of(self.green()))
```

Whether the argument order is `(start, len)` or `(len, start)` is not the most clear at the use site. Just as an example, here's the snippet with the argument order flipped:

```rust
        TextRange::from_len(TextSize::of(self.green()), self.offset)
```

I'd _almost_ say that reads better!

I'm not certain if we can do objectively better, though. This has been the hard case of the standard construction cases we want to explicitly support.

**Comment by matklad** [comment]
Yeah.... The awful, terrible mnemonic is that `from len` can be read as "from len" or "from, len", both of which are correct. It seems unlikely that we'd come with a better name at this point, and I feel pretty strongly that we need a function with this signature, and not a fancier operator/builder API

**Comment by CAD97** [comment]
Wait... `from_offset`!

**Comment by matklad** [comment]
Hm, maybe just ... `TextRange::at(self.offset, TextSize::of(self.green()))`?
