### ISSUE TITLE
What should we call the TextSize::of trait?

### ISSUE THREAD

**Issue by CAD97** [rust-analyzer/text-size#38]
Let's actually formally collect some opinion and make a real decision.

The trait in question:

```rust
/// A reference to a text-like structure that has a textual size.
trait TextSizeOf: Copy {
    /// The size of this text-like.
    fn text_size_of(self) -> TextSize;
}

impl TextSizeOf for &str {}
impl TextSizeOf for char {}
// plus impls for things that would deref coerce to &str

fn TextSize::of(text: impl TextSizeOf) -> TextSize {
    text.text_size_of()
}
```

Options that have been used during development:

- `TextSized::text_size`
- `LenTextSize::len_text_size` (current)

Other potential options:

- trait
  - `TextLen`
  - `LenText`
  - `Text`
- fn
  - `text_len`
  - `len`

For the most part, this function is not meant to be used directly, like `FromStr` is used via `str::parse`; instead, consumers will call `TextSize::of`. (It's for this reason that the trait is designed to be implemented on `Copy` handles and taken by value.) However, especially because [deref coercion does not occur when passing to a generic type](https://users.rust-lang.org/t/why-does-deref-coercion-not-occur-here/40035?u=cad97), _implementing_ the type is expected to not be uncommon.

**Comment by CAD97** [comment]
My personal opinion arguments:

- `TextSized` is too close to `TextSize`; that's why I changed it to the uglier `LenTextSize`.
- `LenTextSize` is ugly but functional and descriptive.
- `TextLen::text_len` would line up most with rowan's current API, which provides `fn text_len(&self) -> TextUnit` for its green types.

**Comment by matklad** [comment]
I like `TextLen` most, but neither is too bad.
