### ISSUE TITLE
Duplicate of functionality in Rowan?

### ISSUE THREAD

**Issue by cmyr** [rust-analyzer/text-size#48]
I see that [rowan](https://docs.rs/rowan/0.12.6/rowan/) has `TextSize` and `TextRange` which seem to duplicate `TextUnit` and `TextRange`, here. Is there some rationale here, or is it a historical artifact?

**Comment by matklad** [comment]
those are re-exports from `text-size`.

**Comment by cmyr** [comment]
Thanks @matklad 😅
