### ISSUE TITLE
#[cfg_attr(feature="serde", derive(Serialize, Deserialize))]

### ISSUE THREAD

**Issue by Matthias-Fauconneau** [rust-analyzer/text-size#49]
Would be nice to have to avoid having to duplicate and convert to a local type

**Comment by matklad** [comment]
already supported https://github.com/rust-analyzer/text-size/blob/master/Cargo.toml#L16

**Comment by Matthias-Fauconneau** [comment]
Thanks, I had not spotted this :)
Would it be possible to get this for text edit as well ?
https://github.com/Matthias-Fauconneau/rust-analyzer/commit/7d1fa8a673b7da8062963cddaa45a1e891b0cf4f#diff-ba2fdfc15306533787b784c62e5a36b9a08d5695f6e87dd8d300bd9a20e6c3ea
