### ISSUE TITLE
Why TextRange doesn't implement Ord & PartialOrd?

### ISSUE THREAD

**Issue by chris-laplante** [rust-analyzer/text-size#50]
I see that `TextRange` has an `ordering` method, but why doesn't it just implement `Ord` and `PartialOrd`? Would you accept a pull request to implement them?

**Comment by matklad** [comment]
There's no meaningful unambiguous default order of ranges. What's the order of `(2, 4)` and `(3, 5)` ? I can imagine several answers. Thus, if the caller wants to order the ranges, they need to be explicit about which ordering do they want, instead of just relying on `<`
